title: Santhosh Kumar Sankar | Aerospace Engineer
description: 7+ years R&D in Aerodynamics • CFD • eVTOL | Full work rights in Australia

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://sandejarvis.github.io"
baseurl: "/santhoshaero"

# Sci-fi navigation
header_pages:
  - index.md
  - aerodynamic-analysis.md
  - cfd.md
  - tools.md
