title: Santhosh Kumar Sankar | Aerospace Engineer
description: Futuristic Aerodynamics • CFD • eVTOL R&D | 7+ years international experience | Full work rights Australia

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://sandejarvis.github.io"
baseurl: "/santhoshaero"
