title: Santhosh Kumar Sankar | Engineering Portfolio
email: santhoshaero008@gmail.com
description: >- 
  Aerospace & Systems Engineer specializing in Fluid Dynamics and R&D Automation.
baseurl: "" 
url: "https://SandeJarvis.github.io"

# Markdown settings
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
